spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/com/onlineshopping/mapper/*.xml
  type-aliases-package: com.onlineshopping.model.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
